### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/doctors

###
GET {{url}}/doctors/6

###
GET {{url}}/doctors/speciality/empty

###
GET {{url}}/doctors/birthday/range/1970-01-01/1981-01-01

###

POST {{url}}/doctors
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "My created doctor",
  "dateOfBirth": "2023-01-01",
  "yearOfGraduation": 2010,
  "clinic": "My clinic",
  "speciality": "mySpeciality"
}

###
PUT {{url}}/doctors/6
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": 123
}

###
DELETE {{url}}/doctors/6
